-- Start of DDL Script for Table LULO97.ERRORS
-- Generated 08-Dec-2024 09:50:47 from LULO97@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = XE)))

CREATE TABLE errors
    (id NUMBER,
    code VARCHAR2(200 BYTE),
    description VARCHAR2(4000 BYTE))
  SEGMENT CREATION IMMEDIATE
  PCTFREE     10
  PCTUSED     40
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  system
  STORAGE   (
    INITIAL     65536
    NEXT        1048576
    MINEXTENTS  1
    MAXEXTENTS  2147483645
  )
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/





-- End of DDL Script for Table LULO97.ERRORS

-- Start of DDL Script for Table LULO97.LOGS
-- Generated 08-Dec-2024 09:50:47 from LULO97@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = XE)))

CREATE TABLE logs
    (id NUMBER,
    time DATE,
    errorcode VARCHAR2(200 BYTE),
    errormsg VARCHAR2(4000 BYTE),
    backtrace VARCHAR2(4000 BYTE),
    errorstack VARCHAR2(4000 BYTE),
    content VARCHAR2(4000 BYTE))
  SEGMENT CREATION IMMEDIATE
  PCTFREE     10
  PCTUSED     40
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  system
  STORAGE   (
    INITIAL     65536
    NEXT        1048576
    MINEXTENTS  1
    MAXEXTENTS  2147483645
  )
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/





-- End of DDL Script for Table LULO97.LOGS

-- Start of DDL Script for Table LULO97.TODOS
-- Generated 08-Dec-2024 09:50:47 from LULO97@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = XE)))

CREATE TABLE todos
    (id NUMBER,
    name VARCHAR2(200 BYTE),
    description VARCHAR2(200 BYTE))
  SEGMENT CREATION IMMEDIATE
  PCTFREE     10
  PCTUSED     40
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  system
  STORAGE   (
    INITIAL     65536
    NEXT        1048576
    MINEXTENTS  1
    MAXEXTENTS  2147483645
  )
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/





-- End of DDL Script for Table LULO97.TODOS

